### ISSUE TITLE
Is there some guides or demo

### ISSUE THREAD

**Issue by lyrachord** [ZachOhara/JavaFX-Material#1]
Hi Zach,
Interesting project.
Is there some guides or demo?
BTW Materialish project is an addition to this project?

Cheers
Chord

**Comment by ZachOhara** [comment]
Hi Lyrachord,

Materialish was designed to supercede and completely replace this project, and it uses a lot of the same code. It started as a support library for a different (very specific) project so I'm not sure there will be much here that's useful to anyone else.

Both projects were suspended almost a year ago, but if I remember correctly, the difference between JavaFX-Material and Materialish is that JavaFX-Material is for applications that are trying to exactly imitate Google's material style, and Materialish is meant for projects that want to only incorporate some aspects of it (such as the fonts, the colors, the motion of some visual elements, etc.). In other words, JavaFx-Material is a self-contained platform, while Materialish is only a library.

As it currently stands, I have no intention of writing any documentation, let alone even finishing it. The best resource I could point you to here is the Google's own design spec for materialism, available here at https://material.io/guidelines/

Neither JavaFx-Material nor Materialish are ready to stand alone as individual projects, but hopefully you may find some snippets that may be useful.

Zach

**Comment by lyrachord** [comment]
Hi Zach,
Thank you for details.

I'm working a simple module build tool for java 9, and plan to make a javafx terminal.
I will try to apply material design to UI.

Because of Jigsaw modularization, it seems JavaFX group's work is not so brilliant:-) and other libraries are not so easy to switch into. I think your projects maybe a great bootstrap point:-)
Anyway, I will still give it a try.

Chord
